[package]
name = "aoc"
version = "1.0.0"

[[bin]]
name = "aoc"
path = "2019/10.rs"

[dependencies]
regex = "1"
lazy_static = "*"
#termion = { git = "https://gitlab.redox-os.org/Jezza/termion", branch = "windows-support" }
permutohedron = "*"