[package]
name = "2016"
version = "1.0.0"
edition = "2018"

[[bin]]
name = "2016"
path = "2017/4.rs"

[dependencies]
regex = "1"
lazy_static = "*"
termion = { git = "https://gitlab.redox-os.org/Jezza/termion", branch = "windows-support" }
permutohedron = "*"